-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 13:43:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boeken
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boeken
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boeken` DEFAULT CHARACTER SET utf8 ;
USE `boeken` ;

-- -----------------------------------------------------
-- Table `boeken`.`boek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`boek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titel` VARCHAR(100) NOT NULL,
  `datumbegin` DATE NOT NULL,
  `datumeind` DATE NOT NULL,
  `kortebeschrijving` VARCHAR(255) NOT NULL,
  `label_id` INT NOT NULL,
  `schrijver_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`label` (
  `label_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`label_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`schrijver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`schrijver` (
  `schrijver_id` INT NOT NULL AUTO_INCREMENT,
  `schrijvernaam` VARCHAR(45) NOT NULL,
  `datumgebor` DATE NOT NULL,
  `datumover` DATE NULL,
  `schrijverplaats` VARCHAR(45) NULL,
  PRIMARY KEY (`schrijver_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genreNaam` VARCHAR(45) NOT NULL,
  `genreInhoud` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`boek_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`boek_has_genre` (
  `id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`, `genre_id`),
  INDEX `fk_boek_has_genre_genre1_idx` (`genre_id` ASC),
  INDEX `fk_boek_has_genre_boek_idx` (`id` ASC),
  CONSTRAINT `fk_boek_has_genre_boek`
    FOREIGN KEY (`id`)
    REFERENCES `boeken`.`boek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boek_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `boeken`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`boek_has_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`boek_has_label` (
  `id` INT NOT NULL,
  `label_id` INT NOT NULL,
  PRIMARY KEY (`id`, `label_id`),
  INDEX `fk_boek_has_label_label1_idx` (`label_id` ASC),
  INDEX `fk_boek_has_label_boek1_idx` (`id` ASC),
  CONSTRAINT `fk_boek_has_label_boek1`
    FOREIGN KEY (`id`)
    REFERENCES `boeken`.`boek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boek_has_label_label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `boeken`.`label` (`label_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`boek_has_schrijver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`boek_has_schrijver` (
  `id` INT NOT NULL,
  `schrijver_id` INT NOT NULL,
  PRIMARY KEY (`id`, `schrijver_id`),
  INDEX `fk_boek_has_schrijver_schrijver1_idx` (`schrijver_id` ASC),
  INDEX `fk_boek_has_schrijver_boek1_idx` (`id` ASC),
  CONSTRAINT `fk_boek_has_schrijver_boek1`
    FOREIGN KEY (`id`)
    REFERENCES `boeken`.`boek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boek_has_schrijver_schrijver1`
    FOREIGN KEY (`schrijver_id`)
    REFERENCES `boeken`.`schrijver` (`schrijver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boeken`.`gebruiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boeken`.`gebruiker` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `uName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `repeatPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
